
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 29;
  public static final int OVER = 25;
  public static final int LPAREN = 27;
  public static final int SEMI = 31;
  public static final int REPEAT = 13;
  public static final int INT = 3;
  public static final int ARRAY = 39;
  public static final int FOR = 32;
  public static final int MINUS = 23;
  public static final int WRITE = 16;
  public static final int RPAREN = 28;
  public static final int NOT = 8;
  public static final int AND = 6;
  public static final int LT = 21;
  public static final int OR = 7;
  public static final int COMMA = 37;
  public static final int BOOL = 4;
  public static final int BEGIN = 5;
  public static final int UNTIL = 14;
  public static final int NUM = 18;
  public static final int PLUS = 22;
  public static final int ASSIGN = 19;
  public static final int IF = 9;
  public static final int ID = 17;
  public static final int OF = 40;
  public static final int EOF = 0;
  public static final int RBRACKET = 30;
  public static final int error = 1;
  public static final int MOD = 26;
  public static final int EQ = 20;
  public static final int TIMES = 24;
  public static final int COLON = 36;
  public static final int ELSE = 11;
  public static final int POINT = 38;
  public static final int READ = 15;
  public static final int TO = 34;
  public static final int WHILE = 33;
  public static final int THEN = 10;
  public static final int END = 12;
  public static final int VAR = 2;
  public static final int DO = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "INT",
  "BOOL",
  "BEGIN",
  "AND",
  "OR",
  "NOT",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "LT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "FOR",
  "WHILE",
  "TO",
  "DO",
  "COLON",
  "COMMA",
  "POINT",
  "ARRAY",
  "OF"
  };
}

